// ════════════════════════════════════════════════════════════
//  VOKABELN – Meisterkurs Keramik
//  Hier können Vokabeln hinzugefügt, geändert oder entfernt werden.
//
//  Struktur jeder Vokabel:
//  {
//    cat:  "Kategoriename",   ← Kategorie (z.B. "Rohstoffe", "Brenntechnik")
//    term: "Fachbegriff",     ← Der Begriff
//    def:  "Erklärung..."     ← Die Definition
//  }
//
//  Neue Vokabel hinzufügen – einfach eine neue Zeile einfügen:
//  {cat:'Rohstoffe', term:'Neuer Begriff', def:'Erklärung des Begriffs'},
// ════════════════════════════════════════════════════════════

const VOK_DATA = [
  // ROHSTOFFE
  {cat:'Rohstoffe',term:'Absorptionsvermögen',def:'Bestreben, Wasser an der Oberfläche anzusammeln – Valenzen nicht gesättigt (Ton/Kaolin)'},
  {cat:'Rohstoffe',term:'Alkalien',def:'1. Hauptgruppe; sehr reaktionsfreudig; 1 Valenzelektron; kommen nur gebunden vor'},
  {cat:'Rohstoffe',term:'Bentonite',def:'Montmorillionite – alle quellfähigen 3-Schicht-Minerale'},
  {cat:'Rohstoffe',term:'Bildsamkeit',def:'Eigenschaft eines festen Körpers, sich zu verformen ohne Teilchenabriss'},
  {cat:'Rohstoffe',term:'Chemische Verwitterung',def:'Chemisches Zerkleinern der Gesteine durch Wasser/Säuren'},
  {cat:'Rohstoffe',term:'Dreischicht-Silikate',def:'Tetraeder – Oktaeder – Tetraeder Aufbau (z.B. Montmorillonit)'},
  {cat:'Rohstoffe',term:'Erdalkalien',def:'2. Hauptgruppe; weniger reaktionsfreudig; 2 Valenzelektronen; nur gebunden in der Natur'},
  {cat:'Rohstoffe',term:'Eutektikum',def:'Mischungsverhältnis zweier Stoffe, das den niedrigsten Schmelzpunkt enthält'},
  {cat:'Rohstoffe',term:'Feldspat',def:'Häufigste Mineralgruppe der Erdkruste – durch Verwitterung zu Kaolin/Ton zerfallen'},
  {cat:'Rohstoffe',term:'Flussmittel',def:'Alkalien/Erdalkalien; erleichtern das Schmelzen (Feldspäte, Kalk, Wollastonit)'},
  {cat:'Rohstoffe',term:'Gestein',def:'Gemenge aus verschiedenen Mineralen'},
  {cat:'Rohstoffe',term:'Kaolin',def:'Verwitterungsprodukt aus Gesteinen (Primäre Lagerstätte), enthält etwas Feldspat/Quarz/Glimmer'},
  {cat:'Rohstoffe',term:'Magerungsmittel',def:'Hoher Schmelzpunkt, keine frühen Eutektika; erhöht Porosität, verringert Brennschwindung'},
  {cat:'Rohstoffe',term:'Magmatische Gesteine',def:'Magmatite → Granit, Basalt (durch Aufschmelzung metamorpher Gesteine)'},
  {cat:'Rohstoffe',term:'Mechanische Verwitterung',def:'Verwitterung durch mechanischen Einfluss (Temperaturwechsel, Wind, Wasser, Wurzelsprengung)'},
  {cat:'Rohstoffe',term:'Metamorphe Gesteine',def:'→ Schiefer, Marmor (durch Wärme/Druck aus Sedimentgesteinen)'},
  {cat:'Rohstoffe',term:'Minerale',def:'Natürlicher, anorganischer homogener Festkörper, meist in Kristallform'},
  {cat:'Rohstoffe',term:'Primäre Lagerstätte',def:'Ort der Entstehung (z.B. Kaolin durch Verwitterung vor Ort)'},
  {cat:'Rohstoffe',term:'Quarz',def:'Extrem hartes, verwitterungsresistentes Mineral (SiO₂)'},
  {cat:'Rohstoffe',term:'Quellvermögen',def:'Fähigkeit Zwischenwasser zu binden: Kaolin = kaum; Montmorillonit = sehr viel'},
  {cat:'Rohstoffe',term:'Sedimentäre Gesteine',def:'→ Kalkstein, Tongesteine (Verwitterung magmatischer Gesteine)'},
  {cat:'Rohstoffe',term:'Sedimentation',def:'Ablagerung von Teilchen nach Schwebevermögen – schwer unten, leicht oben'},
  {cat:'Rohstoffe',term:'Sekundäre Lagerstätte',def:'Durch Umschichtung/Sedimentation (z.B. Tonlagerstätte)'},
  {cat:'Rohstoffe',term:'Tonminerale',def:'Schichtsilikate der kristallinen Gruppe'},
  {cat:'Rohstoffe',term:'Zweischicht-Silikate',def:'Kaolinitgruppe / Tetraeder-Oktaeder-Aufbau / wenig bildsam und quellfähig'},
  {cat:'Rohstoffe',term:'Zwischenschichtwasser',def:'Zwischen den Schichten (Tetra-Okta-Tetra) angelagertes Wasser'},
  // CHEMIE
  {cat:'Chemie',term:'Atombindung',def:'Bindung zwischen Nichtmetallen – Atome teilen gemeinsame Elektronenpaare (Oktettregel)'},
  {cat:'Chemie',term:'Basen',def:'Stoffe, die Protonen aufnehmen oder OH⁻ abgeben; pH-Wert > 7'},
  {cat:'Chemie',term:'Elektronegativität',def:'Maß der Fähigkeit eines Atoms, Bindungselektronen zu sich zu ziehen'},
  {cat:'Chemie',term:'Endotherme Reaktion',def:'Chemische Reaktion, bei der Energie aufgenommen wird (z.B. Kaolinit-Zerfall)'},
  {cat:'Chemie',term:'Exotherme Reaktion',def:'Chemische Reaktion, bei der Wärme abgegeben wird (z.B. Verbrennung, Oxidation)'},
  {cat:'Chemie',term:'Ionenbindung',def:'Bindung zwischen Metallen und Nichtmetallen durch Elektronenübertragung'},
  {cat:'Chemie',term:'Isotope',def:'Selbes Element mit unterschiedlicher Neutronenanzahl (andere Masse, gleiche chem. Eigenschaften)'},
  {cat:'Chemie',term:'Laugen',def:'Wässrige Lösung von Basen'},
  {cat:'Chemie',term:'mol',def:'SI-Einheit der Stoffmenge: 6,022×10²³ Teilchen (Avogadro-Konstante)'},
  {cat:'Chemie',term:'Molare Masse',def:'Masse eines Stoffes pro Stoffmenge [g/mol]'},
  {cat:'Chemie',term:'Oktettregel',def:'Atome streben volle Außenschale an: 8 Valenzelektronen (außer H/He: 2)'},
  {cat:'Chemie',term:'pH-Wert',def:'Maß für sauren/basischen Charakter einer Lösung (0=stark sauer, 7=neutral, 14=stark basisch)'},
  {cat:'Chemie',term:'Resublimieren',def:'Aggregatsänderung: gasförmig → fest'},
  {cat:'Chemie',term:'Säuren',def:'Stoffe, die Protonen abgeben; pH-Wert < 7'},
  {cat:'Chemie',term:'Schalenmodell',def:'Atommodell mit Elektronen auf Schalen um den Atomkern (begrenzte Plätze je Schale)'},
  {cat:'Chemie',term:'Schmelzen',def:'Aggregatsänderung: fest → flüssig'},
  {cat:'Chemie',term:'Sublimieren',def:'Aggregatsänderung: fest → gasförmig'},
  {cat:'Chemie',term:'Valenzelektronen',def:'Elektronen auf der äußersten Schale eines Atoms – bestimmen die Bindungsfähigkeit'},
  {cat:'Chemie',term:'Verdampfen',def:'Aggregatsänderung: flüssig → gasförmig'},
  {cat:'Chemie',term:'Erstarren',def:'Aggregatsänderung: flüssig → fest'},
  // WÄRMELEHRE / BRENNTECHNIK
  {cat:'Wärmelehre',term:'Absolute Feuchte',def:'Aktueller Wassergehalt in kg/kg Reinluft'},
  {cat:'Wärmelehre',term:'Brennkurve',def:'Fahrplan eines Ofens unter Berücksichtigung kritischer Ereignisse (z.B. Quarzsprung bei 573°C)'},
  {cat:'Wärmelehre',term:'Brennschwindung',def:'Volumenverlust eines keramischen Formlings beim Brennen'},
  {cat:'Wärmelehre',term:'Enthalpie',def:'Energiegehalt eines thermodynamischen Systems'},
  {cat:'Wärmelehre',term:'Gesamtschwindung',def:'Komplette Schwindung Grünzustand → gebrannt (NICHT TS+BS addieren!)'},
  {cat:'Wärmelehre',term:'Lambda (λ)',def:'Verhältnis tatsächlich zugeführte Luft / theoretisch nötige Luft. λ=1 neutral, <1 reduzierend, >1 oxidierend'},
  {cat:'Wärmelehre',term:'Neutrale Verbrennung',def:'λ=1: optimales Gas-Luft-Verhältnis – vollständige Verbrennung ohne Über-/Unterschuss'},
  {cat:'Wärmelehre',term:'Oxidierende Verbrennung',def:'λ>1: Luftüberschuss – O₂ im Abgas; verhindert schwarze Kerne'},
  {cat:'Wärmelehre',term:'Primärluft',def:'Luft, die aktiv am Verbrennungsprozess beteiligt ist und direkt reagiert'},
  {cat:'Wärmelehre',term:'Diffusionsluft',def:'Nicht an Verbrennung beteiligt – sorgt für Konvektion im Ofen und hilft beim Kühlen'},
  {cat:'Wärmelehre',term:'Reduzierende Verbrennung',def:'λ<1: Luftmangel – CO im Abgas; Gefahr schwarze Kerne; für Spezialglasuren teils gewünscht'},
  {cat:'Wärmelehre',term:'Relative Feuchte',def:'Verhältnis momentaner Wasserdampfdruck zu Sättigungsdampfdruck [%]'},
  {cat:'Wärmelehre',term:'Schmelzwärme',def:'Energie, die benötigt wird, um einen Stoff vom festen in den flüssigen Zustand zu überführen'},
  {cat:'Wärmelehre',term:'Trockenschwindung',def:'Schwindung des Formlings während des Trockenprozesses'},
  {cat:'Wärmelehre',term:'Quarzsprung',def:'Bei 573°C: sprunghafte Ausdehnung der Quarzkörnchen (α→β-Quarz). Beim Abkühlen: β→α'},
  {cat:'Wärmelehre',term:'Schwarze Kerne',def:'Reduktionskerne – unverbrannte Organik im Scherben (zu wenig Sauerstoff bis 800°C)'},
  {cat:'Wärmelehre',term:'Stöchiometrisch',def:'Neutrale Verbrennung (λ=1): Brennstoff und Luft vollständig verbrannt'},
  {cat:'Wärmelehre',term:'Zündgrenzen',def:'Bereich der zündfähigen Gas-Luft-Gemische: Erdgas UEG=5%, OEG=15% Gasanteil'},
  {cat:'Wärmelehre',term:'Brennwert Ho',def:'Wärmemenge bei Rauchgas unter 100°C – Kondensationswärme wird genutzt (Brennwertkessel)'},
  {cat:'Wärmelehre',term:'Heizwert Hu',def:'Wärmemenge bei Rauchgas über 100°C – Kondensationswärme ungenutzt. In der Keramik immer Hu!'},
  {cat:'Wärmelehre',term:'Wärmestrahlung',def:'Elektromagnetische Wellen – kein Medium nötig; steigt mit T⁴; relevant ab ~700°C im Ofen'},
  {cat:'Wärmelehre',term:'Konvektion',def:'Wärmeübertragung durch bewegtes Gas/Flüssigkeit; dominiert bis ~700°C; erzwungen > frei'},
  {cat:'Wärmelehre',term:'Wärmeleitung',def:'Übertragung durch direkte Berührung; wichtig für Durchheizung des Scherbens'},
  // MSR
  {cat:'MSR',term:'2-Punkt-Regler',def:'Einfachster Regler: Stellglied kennt nur An (100%) oder Aus (0%) – Hysterese!'},
  {cat:'MSR',term:'3-Punkt-Regler',def:'Drei Zustände: z.B. Heizen / Totzone / Kühlen'},
  {cat:'MSR',term:'Ausgleichszeit (Tg)',def:'Zeit, bis die Strecke nach einer Störung ihren neuen stabilen Endzustand erreicht'},
  {cat:'MSR',term:'D-Regler',def:'Differenzial: reagiert auf Änderungsgeschwindigkeit; dämpft Überschwingen; empfindlich auf Rauschen'},
  {cat:'MSR',term:'Eichen',def:'Gesetzlich vorgeschriebene Prüfung eines Messgeräts durch das Eichamt'},
  {cat:'MSR',term:'I-Regler',def:'Integral: integriert Abweichung über Zeit; keine bleibende Abweichung; neigt zum Überschwingen'},
  {cat:'MSR',term:'Justieren',def:'Verstellen eines Geräts auf korrekte Werte (Eingriff ins Gerät)'},
  {cat:'MSR',term:'Kalibrieren',def:'Vergleich mit Normal ohne Eingriff – Feststellung der Abweichung (kein Eingriff!)'},
  {cat:'MSR',term:'P-Regler',def:'Proportional: Stellgröße proportional zur Abweichung – hat immer bleibende Regelabweichung'},
  {cat:'MSR',term:'PID-Regler',def:'Kombination P+I+D: präzise, schnell, stabil – aufwendig einzustellen'},
  {cat:'MSR',term:'Regelkreis',def:'Geschlossener Kreislauf: Messen → Vergleich Soll/Ist → Regeln → Messen...'},
  {cat:'MSR',term:'Regelstrecke',def:'Zu regelndes System (z.B. Ofen, Mühle)'},
  {cat:'MSR',term:'Stellglied',def:'Bauteil, das den Massen- oder Energiestrom direkt beeinflusst (z.B. Ventil)'},
  {cat:'MSR',term:'Stellgröße',def:'Ausgangsgröße des Reglers, die das Stellglied ansteuert (z.B. Ventilöffnung in %)'},
  {cat:'MSR',term:'Steuern',def:'Offene Wirkungskette – kein Soll/Ist-Vergleich, keine Rückkopplung'},
  {cat:'MSR',term:'Regeln',def:'Geschlossener Regelkreis mit Rückkopplung – Istwert wird ständig erfasst und verglichen'},
  {cat:'MSR',term:'Störgröße',def:'Externer Einfluss, der den Regelkreis stört (z.B. offene Ofentür, Luftzug)'},
  {cat:'MSR',term:'Strecke mit Ausgleich',def:'Stabile Strecke: Regelgröße pendelt sich bei konstantem Eingang auf Endwert ein'},
  {cat:'MSR',term:'Strecke ohne Ausgleich',def:'Integrierende Strecke: Regelgröße steigt/fällt unaufhörlich (z.B. Füllstand)'},
  {cat:'MSR',term:'Streckenverstärkung (Ks)',def:'Verhältnis Ausgangsänderung / Eingangsänderung der Regelstrecke'},
  {cat:'MSR',term:'Verzugszeit (Tu)',def:'Zeit bis erste Reaktion nach Störung – klein=gut regelbar, groß=träge Strecke'},
  // AUFBEREITUNG / FORMGEBUNG
  {cat:'Aufbereitung',term:'Backenbrecher',def:'Grobzerkleinerungsmaschine mit feststehender und beweglicher Backe'},
  {cat:'Aufbereitung',term:'Bechertaktstraße',def:'Automatisierte Methode zur Massenherstellung von Hohlguss (ersetzt Eindrehen)'},
  {cat:'Aufbereitung',term:'Drachenzähne',def:'Pressfehler beim Strangpressen durch unterschiedliche Wandreibung an Kanten'},
  {cat:'Aufbereitung',term:'Druckschlickerguss',def:'Moderne Gießtechnik: Schlicker mit Druck (bis 40 bar) in PU-Form – kurze Zykluszeiten'},
  {cat:'Aufbereitung',term:'Isostatisches Pressen',def:'Druck von allen Seiten (über Membran/Flüssigkeit) – gleichmäßige Verdichtung, kein Material-"Gedächtnis"'},
  {cat:'Aufbereitung',term:'Kaskadenwirkung',def:'Reibende Mahlwirkung in der Trommelmühle – rundes Korn – langsame Drehzahl (n=25/√Ø)'},
  {cat:'Aufbereitung',term:'Katarktwirkung',def:'Schlagende Mahlwirkung in der Trommelmühle – splittriges Korn – schnellere Drehzahl (n=30/√Ø)'},
  {cat:'Aufbereitung',term:'Klassieren',def:'Trennen eines Korngemisches in zwei Korngrößen (Sieben)'},
  {cat:'Aufbereitung',term:'Fraktionieren',def:'Trennen in mehrere Korngrößen (Siebturm)'},
  {cat:'Aufbereitung',term:'Kollergang',def:'Gelochte Mahlbahn + Läufer an Königswelle – Mischen/Homogenisieren plastischer Massen'},
  {cat:'Aufbereitung',term:'Schlicker',def:'Gießfähige keramische Suspension für die Gießformgebung'},
  {cat:'Aufbereitung',term:'Texturen (Strangpressen)',def:'Ausrichtung der Tonmineralplättchen durch unterschiedliche Stranggeschwindigkeiten außen/innen'},
  {cat:'Aufbereitung',term:'Thixotropie',def:'Bei Bewegung flüssig, in Ruhe geliert – wichtige Eigenschaft von Gießschlicker'},
  {cat:'Aufbereitung',term:'Trommelmühle',def:'Feinmahlung von Rohstoffen oder Glasuren, nass oder trocken'},
  {cat:'Aufbereitung',term:'Vakuumstrangpresse',def:'Formgebung plastischer Massen durch Extrusion unter Vakuum (z.B. Ziegelherstellung)'},
  {cat:'Aufbereitung',term:'Winkler-Diagramm',def:'Analyse der Korngrößenverteilung → Vorhersage der Eignung eines Tons'},
  {cat:'Aufbereitung',term:'Sumpfhaus / Maukturm',def:'Homogenisierung der Feuchteverteilung in keramischen Massen durch Lagerung'},
  {cat:'Aufbereitung',term:'Engobe',def:'Tonartiger, diffusionsoffener Überzug für Dekorzwecke oder als Haftvermittler'},
  // FACHRECHNEN / LABOR
  {cat:'Fachrechnen',term:'Anmachwasser (AW)',def:'Zusatzwasser, bezogen auf Masse trocken. AW = m_Wasser/m_trocken · 100%'},
  {cat:'Fachrechnen',term:'Feuchte (f)',def:'Wasseranteil, bezogen auf Masse feucht. f = m_Wasser/m_feucht · 100%'},
  {cat:'Fachrechnen',term:'DSA',def:'Dehnungsschwindungsanalyse (Dilatometer) – Längenänderung über Temperatur'},
  {cat:'Fachrechnen',term:'EMA',def:'Erhitzungsmikroskop – charakteristische Schmelzpunkte (Anfang, Halbkugel, Fließpunkt)'},
  {cat:'Fachrechnen',term:'Fließpunkt',def:'Probe ist auf 1/3 ihrer ursprünglichen Höhe zerflossen'},
  {cat:'Fachrechnen',term:'Glühverlust (GV)',def:'Masseverlust beim Brennen: Organik, CO₂, Kristallwasser – in % der Trockenmasse'},
  {cat:'Fachrechnen',term:'Halbkugelpunkt',def:'Höhe = halbe Breite der Basis – gilt als Schmelztemperatur des Rohstoffs'},
  {cat:'Fachrechnen',term:'Litergewicht',def:'Masse der Trockensubstanz in 1 Liter Suspension [g/l]'},
  {cat:'Fachrechnen',term:'Masse feucht',def:'Masse inkl. Anmachwasser (= m_trocken + m_Wasser)'},
  {cat:'Fachrechnen',term:'Masse trocken',def:'Masse bei 0% Feuchte (im Trockenschrank bei 110°C bis zur Gewichtskonstanz)'},
  {cat:'Fachrechnen',term:'Offene Poren',def:'Poren mit Verbindung zur Oberfläche – mit Wasser tränkbar; bestimmen die Wasseraufnahme'},
  {cat:'Fachrechnen',term:'Geschlossene Poren',def:'Keine Verbindung zur Oberfläche – nicht mit Wasser tränkbar'},
  {cat:'Fachrechnen',term:'PCTR-Ringe',def:'Process Temperature Control Rings – Kontrolle der Wärmearbeit in der Ware'},
  {cat:'Fachrechnen',term:'Porosität',def:'Verhältnis Porenvolumen zu Gesamtvolumen [%]'},
  {cat:'Fachrechnen',term:'Reindichte',def:'Dichte ohne Poren ρ_r [g/cm³] – nur reines Material'},
  {cat:'Fachrechnen',term:'Rohdichte',def:'Dichte inkl. aller Poren ρ_0 [g/cm³] – Körper als Ganzes'},
  {cat:'Fachrechnen',term:'Segerkegel',def:'Temperaturmesskeramik zur Kontrolle der Wärmearbeit im Brand'},
  {cat:'Fachrechnen',term:'TGA',def:'Thermogravimetrische Analyse – Masseverlust über Temperatur'},
  {cat:'Fachrechnen',term:'TQF',def:'Ton–Quarz–Feldspat-Verhältnis. Porzellan-Norm: T=50% | Q=20-25% | F=25-30%'},
  {cat:'Fachrechnen',term:'Trockenbruchfestigkeit (TBF)',def:'Mechanischer Widerstand des getrockneten Grünlings gegen Bruchbelastung'},
  {cat:'Fachrechnen',term:'Viskosität',def:'Maß für die Zähflüssigkeit eines Stoffes – bei Schlickern durch Verflüssiger eingestellt'},
  {cat:'Fachrechnen',term:'Wasseraufnahme (WA)',def:'WA = (m_nass − m_tr) / m_tr · 100% – wie viel Wasser ein Scherben aufnimmt'},
  {cat:'Fachrechnen',term:'XRD',def:'Röntgendiffraktometer – Bestimmung der mineralogischen Zusammensetzung'},
  // FEHLER & ZUSÄTZE
  {cat:'Fehler',term:'Trockenrisse',def:'Entstehen beim Trocknen, besonders an Kanten. Aussehen: stumpf, rau'},
  {cat:'Fehler',term:'Brennrisse',def:'Entstehen beim Aufheizen oder Abkühlen durch Quarzsprung/Thermal-schock. Aussehen: scharf, glatt'},
  {cat:'Fehler',term:'Kapillarabriss',def:'Zu schnelles Trocknen: Wasser kann nicht schnell genug nach außen – Risse im Scherben'},
  {cat:'Fehler',term:'Nadelstiche / Pinholes',def:'Winzige Krater in der Glasur durch Gase (Organik, CO₂) die beim Brand entweichen'},
  {cat:'Fehler',term:'Abplatzer',def:'Glasur springt ab. Ursache: WAK_Glasur << WAK_Scherben → zu starke Druckspannung'},
  {cat:'Fehler',term:'Abroller',def:'Glasur haftet nicht – Verunreinigung auf dem Scherben verhindert Bindung'},
  {cat:'Fehler',term:'Haarrisse / Craquelé',def:'Feines Rissnetz in der Glasur. Ursache: WAK_Glasur > WAK_Scherben → Zugspannung'},
  {cat:'Fehler',term:'Reduktionskerne / Schwarze Kerne',def:'Organik nicht ausgebrannt – zu wenig Sauerstoff bis 800°C (λ zu klein)'},
  {cat:'Fehler',term:'Presslagen',def:'Gefügestörung durch eingeschlossene Luft beim axialen Pressen'},
  {cat:'Fehler',term:'Zugspannungen',def:'Reißen das Material auseinander – Keramik sehr empfindlich (NoGo bei Glasuren!)'},
  {cat:'Fehler',term:'Druckspannungen',def:'Drücken das Material zusammen – stabil; bei Glasuren gezielt durch kleineren WAK_Glasur'},
  {cat:'Fehler',term:'Elektrolyte',def:'Lagern sich an Tonmineralplättchen an und laden diese gleichnamig negativ → Verflüssigung'},
  {cat:'Fehler',term:'Verflüssiger',def:'Chem. Zusätze (Wasserglas, Soda, Polyacrylate) – senken Viskosität des Schlickers massiv'},
  {cat:'Fehler',term:'Polyvinylalkohole (PVA)',def:'Synthetisches, wasserlösliches Polymer – wichtigstes temporäres Bindemittel im Sprühschlicker'},
  {cat:'Fehler',term:'Bindemittel',def:'Verbessern Haftung zwischen unplastischen Teilchen (z.B. Oxidkeramik, Schamotte)'},
  {cat:'Fehler',term:'Presshilfsmittel',def:'Granulier-/Gleitmittel/Bindemittel – verbessern Verpressbarkeit von Sprühgranulat'},
];;